global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    app: spur
rule_files:
  - "alerts.yml"
scrape_configs:
  - job_name: spur-backend
    static_configs:
      - targets: ['backend:9091']
    metrics_path: /metrics
    scrape_interval: 10s
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
