// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikeys.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (
    id,
    tenant_id,
    name,
    type,
    prefix,
    key_hash,
    scopes,
    allowed_origins,
    expires_at
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9
         )
RETURNING id, tenant_id, name, prefix, key_hash, scopes, ip_allowlist, expires_at, created_at, last_used_at, type, allowed_origins
`

type CreateAPIKeyParams struct {
	ID             uuid.UUID `json:"id"`
	TenantID       uuid.UUID `json:"tenant_id"`
	Name           string    `json:"name"`
	Type           string    `json:"type"`
	Prefix         string    `json:"prefix"`
	KeyHash        string    `json:"key_hash"`
	Scopes         []string  `json:"scopes"`
	AllowedOrigins []string  `json:"allowed_origins"`
	ExpiresAt      time.Time `json:"expires_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKeys, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Type,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
		arg.AllowedOrigins,
		arg.ExpiresAt,
	)
	var i ApiKeys
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.IpAllowlist,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Type,
		&i.AllowedOrigins,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys
WHERE id = $1 AND tenant_id = $2
`

type DeleteAPIKeyParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.TenantID)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, tenant_id, name, prefix, key_hash, scopes, ip_allowlist, expires_at, created_at, last_used_at, type, allowed_origins FROM api_keys
WHERE id = $1 AND tenant_id = $2
`

type GetAPIKeyParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKeys, error) {
	row := q.db.QueryRow(ctx, getAPIKey, arg.ID, arg.TenantID)
	var i ApiKeys
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.IpAllowlist,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Type,
		&i.AllowedOrigins,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, tenant_id, name, prefix, key_hash, scopes, ip_allowlist, expires_at, created_at, last_used_at, type, allowed_origins FROM api_keys
WHERE prefix = $1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKeys, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i ApiKeys
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.IpAllowlist,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.Type,
		&i.AllowedOrigins,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, tenant_id, name, prefix, key_hash, scopes, ip_allowlist, expires_at, created_at, last_used_at, type, allowed_origins FROM api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, tenantID uuid.UUID) ([]ApiKeys, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKeys{}
	for rows.Next() {
		var i ApiKeys
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Prefix,
			&i.KeyHash,
			&i.Scopes,
			&i.IpAllowlist,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.Type,
			&i.AllowedOrigins,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
