// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createClient = `-- name: CreateClient :one
INSERT INTO fosite_clients (
    id,
    tenant_id,
    client_secret,
    redirect_uris,
    grant_types,
    response_types,
    scopes,
    audience,
    public,
    active
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
         )
RETURNING id, client_secret, tenant_id, redirect_uris, grant_types, response_types, scopes, audience, public, active, created_at, updated_at
`

type CreateClientParams struct {
	ID            string    `json:"id"`
	TenantID      uuid.UUID `json:"tenant_id"`
	ClientSecret  *string   `json:"client_secret"`
	RedirectUris  []string  `json:"redirect_uris"`
	GrantTypes    []string  `json:"grant_types"`
	ResponseTypes []string  `json:"response_types"`
	Scopes        []string  `json:"scopes"`
	Audience      []string  `json:"audience"`
	Public        bool      `json:"public"`
	Active        bool      `json:"active"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (FositeClients, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.ID,
		arg.TenantID,
		arg.ClientSecret,
		arg.RedirectUris,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.Scopes,
		arg.Audience,
		arg.Public,
		arg.Active,
	)
	var i FositeClients
	err := row.Scan(
		&i.ID,
		&i.ClientSecret,
		&i.TenantID,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Scopes,
		&i.Audience,
		&i.Public,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM fosite_clients
WHERE id = $1
`

func (q *Queries) DeleteClient(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteClient, id)
	return err
}

const getActiveClient = `-- name: GetActiveClient :one
SELECT id, client_secret, tenant_id, redirect_uris, grant_types, response_types, scopes, audience, public, active, created_at, updated_at FROM fosite_clients
WHERE id = $1 AND active = true
`

func (q *Queries) GetActiveClient(ctx context.Context, id string) (FositeClients, error) {
	row := q.db.QueryRow(ctx, getActiveClient, id)
	var i FositeClients
	err := row.Scan(
		&i.ID,
		&i.ClientSecret,
		&i.TenantID,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Scopes,
		&i.Audience,
		&i.Public,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, client_secret, tenant_id, redirect_uris, grant_types, response_types, scopes, audience, public, active, created_at, updated_at FROM fosite_clients
WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id string) (FositeClients, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i FositeClients
	err := row.Scan(
		&i.ID,
		&i.ClientSecret,
		&i.TenantID,
		&i.RedirectUris,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.Scopes,
		&i.Audience,
		&i.Public,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClients = `-- name: ListClients :many
SELECT id, client_secret, tenant_id, redirect_uris, grant_types, response_types, scopes, audience, public, active, created_at, updated_at FROM fosite_clients
WHERE tenant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClients(ctx context.Context, tenantID uuid.UUID) ([]FositeClients, error) {
	rows, err := q.db.Query(ctx, listClients, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FositeClients{}
	for rows.Next() {
		var i FositeClients
		if err := rows.Scan(
			&i.ID,
			&i.ClientSecret,
			&i.TenantID,
			&i.RedirectUris,
			&i.GrantTypes,
			&i.ResponseTypes,
			&i.Scopes,
			&i.Audience,
			&i.Public,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicClients = `-- name: ListPublicClients :many
SELECT id, client_secret, tenant_id, redirect_uris, grant_types, response_types, scopes, audience, public, active, created_at, updated_at FROM fosite_clients
WHERE public = true
ORDER BY created_at DESC
`

func (q *Queries) ListPublicClients(ctx context.Context) ([]FositeClients, error) {
	rows, err := q.db.Query(ctx, listPublicClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FositeClients{}
	for rows.Next() {
		var i FositeClients
		if err := rows.Scan(
			&i.ID,
			&i.ClientSecret,
			&i.TenantID,
			&i.RedirectUris,
			&i.GrantTypes,
			&i.ResponseTypes,
			&i.Scopes,
			&i.Audience,
			&i.Public,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleClientStatus = `-- name: ToggleClientStatus :exec
UPDATE fosite_clients
SET active = $2, updated_at = NOW()
WHERE id = $1
`

type ToggleClientStatusParams struct {
	ID     string `json:"id"`
	Active bool   `json:"active"`
}

func (q *Queries) ToggleClientStatus(ctx context.Context, arg ToggleClientStatusParams) error {
	_, err := q.db.Exec(ctx, toggleClientStatus, arg.ID, arg.Active)
	return err
}

const updateClientConfig = `-- name: UpdateClientConfig :exec
UPDATE fosite_clients
SET
    redirect_uris = $2,
    scopes = $3,
    grant_types = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateClientConfigParams struct {
	ID           string   `json:"id"`
	RedirectUris []string `json:"redirect_uris"`
	Scopes       []string `json:"scopes"`
	GrantTypes   []string `json:"grant_types"`
}

func (q *Queries) UpdateClientConfig(ctx context.Context, arg UpdateClientConfigParams) error {
	_, err := q.db.Exec(ctx, updateClientConfig,
		arg.ID,
		arg.RedirectUris,
		arg.Scopes,
		arg.GrantTypes,
	)
	return err
}

const updateClientSecret = `-- name: UpdateClientSecret :exec
UPDATE fosite_clients
SET client_secret = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateClientSecretParams struct {
	ID           string  `json:"id"`
	ClientSecret *string `json:"client_secret"`
}

func (q *Queries) UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) error {
	_, err := q.db.Exec(ctx, updateClientSecret, arg.ID, arg.ClientSecret)
	return err
}
