// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type TenantKind string

const (
	TenantKindOps      TenantKind = "ops"
	TenantKindCustomer TenantKind = "customer"
)

func (e *TenantKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TenantKind(s)
	case string:
		*e = TenantKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TenantKind: %T", src)
	}
	return nil
}

type NullTenantKind struct {
	TenantKind TenantKind `json:"tenant_kind"`
	Valid      bool       `json:"valid"` // Valid is true if TenantKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTenantKind) Scan(value interface{}) error {
	if value == nil {
		ns.TenantKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TenantKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTenantKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TenantKind), nil
}

type ApiKeys struct {
	ID             uuid.UUID          `json:"id"`
	TenantID       uuid.UUID          `json:"tenant_id"`
	Name           string             `json:"name"`
	Prefix         string             `json:"prefix"`
	KeyHash        string             `json:"key_hash"`
	Scopes         []string           `json:"scopes"`
	IpAllowlist    []netip.Addr       `json:"ip_allowlist"`
	ExpiresAt      time.Time          `json:"expires_at"`
	CreatedAt      time.Time          `json:"created_at"`
	LastUsedAt     pgtype.Timestamptz `json:"last_used_at"`
	Type           string             `json:"type"`
	AllowedOrigins []string           `json:"allowed_origins"`
}

type AuditEvents struct {
	ID             uuid.UUID   `json:"id"`
	ActorUserID    pgtype.UUID `json:"actor_user_id"`
	ActorTenantID  pgtype.UUID `json:"actor_tenant_id"`
	TargetTenantID pgtype.UUID `json:"target_tenant_id"`
	Action         string      `json:"action"`
	Entity         string      `json:"entity"`
	PayloadJson    []byte      `json:"payload_json"`
	RequestID      *string     `json:"request_id"`
	CreatedAt      time.Time   `json:"created_at"`
}

type FositeClients struct {
	ID            string    `json:"id"`
	ClientSecret  *string   `json:"client_secret"`
	TenantID      uuid.UUID `json:"tenant_id"`
	RedirectUris  []string  `json:"redirect_uris"`
	GrantTypes    []string  `json:"grant_types"`
	ResponseTypes []string  `json:"response_types"`
	Scopes        []string  `json:"scopes"`
	Audience      []string  `json:"audience"`
	Public        bool      `json:"public"`
	Active        bool      `json:"active"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

type FositeSessions struct {
	Signature   string          `json:"signature"`
	Type        string          `json:"type"`
	RequestID   string          `json:"request_id"`
	ClientID    string          `json:"client_id"`
	TenantID    uuid.UUID       `json:"tenant_id"`
	Subject     string          `json:"subject"`
	Active      bool            `json:"active"`
	RequestedAt time.Time       `json:"requested_at"`
	ExpiresAt   time.Time       `json:"expires_at"`
	FormData    json.RawMessage `json:"form_data"`
	SessionData json.RawMessage `json:"session_data"`
}

type Modules struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Permissions struct {
	ID          uuid.UUID   `json:"id"`
	Key         string      `json:"key"`
	Description *string     `json:"description"`
	Module      string      `json:"module"`
	ModuleID    pgtype.UUID `json:"module_id"`
}

type RolePermissions struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

type Roles struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Code        *string   `json:"code"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
	IsSystem    bool      `json:"is_system"`
}

type TenantModules struct {
	TenantID  uuid.UUID `json:"tenant_id"`
	ModuleID  uuid.UUID `json:"module_id"`
	Status    string    `json:"status"`
	EnabledAt time.Time `json:"enabled_at"`
}

type Tenants struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Kind             TenantKind         `json:"kind"`
	CreatedAt        time.Time          `json:"created_at"`
	UpdatedAt        time.Time          `json:"updated_at"`
	TrialEndsAt      pgtype.Timestamptz `json:"trial_ends_at"`
	SubscriptionPlan *string            `json:"subscription_plan"`
}

type UserRoles struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

type UserSessions struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Users struct {
	ID                         uuid.UUID          `json:"id"`
	TenantID                   uuid.UUID          `json:"tenant_id"`
	FirstName                  string             `json:"first_name"`
	LastName                   string             `json:"last_name"`
	Email                      string             `json:"email"`
	Mobile                     *string            `json:"mobile"`
	PasswordHash               string             `json:"password_hash"`
	IsSuperAdmin               bool               `json:"is_super_admin"`
	AuthzVersion               int32              `json:"authz_version"`
	IsActive                   bool               `json:"is_active"`
	EmailVerifiedAt            pgtype.Timestamptz `json:"email_verified_at"`
	MobileVerifiedAt           pgtype.Timestamptz `json:"mobile_verified_at"`
	CreatedAt                  time.Time          `json:"created_at"`
	UpdatedAt                  time.Time          `json:"updated_at"`
	VerificationGracePeriodEnd pgtype.Timestamptz `json:"verification_grace_period_end"`
	VerifiedAt                 pgtype.Timestamptz `json:"verified_at"`
	IsLocked                   bool               `json:"is_locked"`
}

type VerificationChallenges struct {
	ID         uuid.UUID          `json:"id"`
	TenantID   uuid.UUID          `json:"tenant_id"`
	UserID     uuid.UUID          `json:"user_id"`
	Kind       string             `json:"kind"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  time.Time          `json:"expires_at"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  time.Time          `json:"created_at"`
}
