// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Role Permissions
	AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error
	AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKeys, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (FositeClients, error)
	CreateModule(ctx context.Context, arg CreateModuleParams) (Modules, error)
	// Permissions
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permissions, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Roles, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenants, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSessions, error)
	CreateVerificationChallenge(ctx context.Context, arg CreateVerificationChallengeParams) (VerificationChallenges, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	DeleteClient(ctx context.Context, id string) error
	DeleteExpiredChallenges(ctx context.Context) error
	DeleteModule(ctx context.Context, id uuid.UUID) error
	DeletePermission(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteSessionByType(ctx context.Context, arg DeleteSessionByTypeParams) (int64, error)
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	DeleteUserByEmail(ctx context.Context, email string) error
	DeleteUserByMobile(ctx context.Context, mobile *string) error
	DeleteUserSession(ctx context.Context, token string) error
	DeleteUserSessionsByUserID(ctx context.Context, userID uuid.UUID) error
	DisableModuleForTenant(ctx context.Context, arg DisableModuleForTenantParams) error
	// Tenant Modules
	EnableModuleForTenant(ctx context.Context, arg EnableModuleForTenantParams) error
	GetAPIKey(ctx context.Context, arg GetAPIKeyParams) (ApiKeys, error)
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKeys, error)
	GetActiveClient(ctx context.Context, id string) (FositeClients, error)
	GetClient(ctx context.Context, id string) (FositeClients, error)
	GetModule(ctx context.Context, id uuid.UUID) (Modules, error)
	GetModuleByCode(ctx context.Context, code string) (Modules, error)
	GetPermission(ctx context.Context, id uuid.UUID) (Permissions, error)
	GetRole(ctx context.Context, arg GetRoleParams) (Roles, error)
	GetRoleByCode(ctx context.Context, arg GetRoleByCodeParams) (Roles, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (Roles, error)
	GetSession(ctx context.Context, arg GetSessionParams) (FositeSessions, error)
	GetSystemRoleByCode(ctx context.Context, code *string) (Roles, error)
	GetTenant(ctx context.Context, id uuid.UUID) (Tenants, error)
	GetUser(ctx context.Context, arg GetUserParams) (Users, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByMobile(ctx context.Context, mobile *string) (Users, error)
	GetUserSessionByToken(ctx context.Context, token string) (GetUserSessionByTokenRow, error)
	GetVerificationChallenge(ctx context.Context, arg GetVerificationChallengeParams) (VerificationChallenges, error)
	GetVerificationChallengeByToken(ctx context.Context, arg GetVerificationChallengeByTokenParams) (VerificationChallenges, error)
	ListAPIKeys(ctx context.Context, tenantID uuid.UUID) ([]ApiKeys, error)
	ListAllRoles(ctx context.Context) ([]Roles, error)
	ListAllUsers(ctx context.Context) ([]Users, error)
	ListClients(ctx context.Context, tenantID uuid.UUID) ([]FositeClients, error)
	ListModules(ctx context.Context) ([]Modules, error)
	ListPermissions(ctx context.Context) ([]Permissions, error)
	ListPermissionsByModule(ctx context.Context, moduleID pgtype.UUID) ([]Permissions, error)
	ListPublicClients(ctx context.Context) ([]FositeClients, error)
	ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]Permissions, error)
	ListRoles(ctx context.Context, tenantID uuid.UUID) ([]Roles, error)
	ListTenantModules(ctx context.Context, tenantID uuid.UUID) ([]Modules, error)
	ListTenants(ctx context.Context) ([]Tenants, error)
	ListUserRoles(ctx context.Context, userID uuid.UUID) ([]Roles, error)
	ListUsers(ctx context.Context, tenantID uuid.UUID) ([]Users, error)
	MarkChallengeConsumed(ctx context.Context, id uuid.UUID) error
	RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error
	RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error
	RevokeSessionByRequestId(ctx context.Context, requestID string) error
	RevokeSessionByRequestIdAndType(ctx context.Context, arg RevokeSessionByRequestIdAndTypeParams) error
	ToggleClientStatus(ctx context.Context, arg ToggleClientStatusParams) error
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateClientConfig(ctx context.Context, arg UpdateClientConfigParams) error
	UpdateClientSecret(ctx context.Context, arg UpdateClientSecretParams) error
	UpdateModule(ctx context.Context, arg UpdateModuleParams) error
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserLockStatus(ctx context.Context, arg UpdateUserLockStatusParams) error
	// Modules
	UpsertModule(ctx context.Context, arg UpsertModuleParams) (Modules, error)
	UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permissions, error)
}

var _ Querier = (*Queries)(nil)
