// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rbac.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignPermissionToRole = `-- name: AssignPermissionToRole :exec

INSERT INTO role_permissions (role_id, permission_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignPermissionToRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

// Role Permissions
func (q *Queries) AssignPermissionToRole(ctx context.Context, arg AssignPermissionToRoleParams) error {
	_, err := q.db.Exec(ctx, assignPermissionToRole, arg.RoleID, arg.PermissionID)
	return err
}

const assignRoleToUser = `-- name: AssignRoleToUser :exec
INSERT INTO user_roles (user_id, role_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AssignRoleToUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) AssignRoleToUser(ctx context.Context, arg AssignRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUser, arg.UserID, arg.RoleID)
	return err
}

const createModule = `-- name: CreateModule :one
INSERT INTO modules (id, code, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, description, created_at
`

type CreateModuleParams struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) CreateModule(ctx context.Context, arg CreateModuleParams) (Modules, error) {
	row := q.db.QueryRow(ctx, createModule,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	var i Modules
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createPermission = `-- name: CreatePermission :one

INSERT INTO permissions (id, key, description, module, module_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, key, description, module, module_id
`

type CreatePermissionParams struct {
	ID          uuid.UUID   `json:"id"`
	Key         string      `json:"key"`
	Description *string     `json:"description"`
	Module      string      `json:"module"`
	ModuleID    pgtype.UUID `json:"module_id"`
}

// Permissions
func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (Permissions, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.ID,
		arg.Key,
		arg.Description,
		arg.Module,
		arg.ModuleID,
	)
	var i Permissions
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.Module,
		&i.ModuleID,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (
    id,
    tenant_id,
    name,
    code,
    description,
    is_system
) VALUES (
             $1, $2, $3, $4, $5, $6
         )
RETURNING id, tenant_id, name, code, description, created_at, is_system
`

type CreateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Code        *string   `json:"code"`
	Description *string   `json:"description"`
	IsSystem    bool      `json:"is_system"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Roles, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.IsSystem,
	)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.IsSystem,
	)
	return i, err
}

const deleteModule = `-- name: DeleteModule :exec
DELETE FROM modules WHERE id = $1
`

func (q *Queries) DeleteModule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteModule, id)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1 AND tenant_id = $2
`

type DeleteRoleParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.TenantID)
	return err
}

const disableModuleForTenant = `-- name: DisableModuleForTenant :exec
DELETE FROM tenant_modules
WHERE tenant_id = $1 AND module_id = $2
`

type DisableModuleForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ModuleID uuid.UUID `json:"module_id"`
}

func (q *Queries) DisableModuleForTenant(ctx context.Context, arg DisableModuleForTenantParams) error {
	_, err := q.db.Exec(ctx, disableModuleForTenant, arg.TenantID, arg.ModuleID)
	return err
}

const enableModuleForTenant = `-- name: EnableModuleForTenant :exec

INSERT INTO tenant_modules (tenant_id, module_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (tenant_id, module_id) DO UPDATE SET status = EXCLUDED.status
`

type EnableModuleForTenantParams struct {
	TenantID uuid.UUID `json:"tenant_id"`
	ModuleID uuid.UUID `json:"module_id"`
	Status   string    `json:"status"`
}

// Tenant Modules
func (q *Queries) EnableModuleForTenant(ctx context.Context, arg EnableModuleForTenantParams) error {
	_, err := q.db.Exec(ctx, enableModuleForTenant, arg.TenantID, arg.ModuleID, arg.Status)
	return err
}

const getModule = `-- name: GetModule :one
SELECT id, code, name, description, created_at FROM modules WHERE id = $1
`

func (q *Queries) GetModule(ctx context.Context, id uuid.UUID) (Modules, error) {
	row := q.db.QueryRow(ctx, getModule, id)
	var i Modules
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getModuleByCode = `-- name: GetModuleByCode :one
SELECT id, code, name, description, created_at FROM modules WHERE code = $1
`

func (q *Queries) GetModuleByCode(ctx context.Context, code string) (Modules, error) {
	row := q.db.QueryRow(ctx, getModuleByCode, code)
	var i Modules
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getPermission = `-- name: GetPermission :one
SELECT id, key, description, module, module_id FROM permissions WHERE id = $1
`

func (q *Queries) GetPermission(ctx context.Context, id uuid.UUID) (Permissions, error) {
	row := q.db.QueryRow(ctx, getPermission, id)
	var i Permissions
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.Module,
		&i.ModuleID,
	)
	return i, err
}

const getRole = `-- name: GetRole :one
SELECT id, tenant_id, name, code, description, created_at, is_system FROM roles
WHERE id = $1 AND tenant_id = $2
`

type GetRoleParams struct {
	ID       uuid.UUID `json:"id"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Roles, error) {
	row := q.db.QueryRow(ctx, getRole, arg.ID, arg.TenantID)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.IsSystem,
	)
	return i, err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, tenant_id, name, code, description, created_at, is_system FROM roles
WHERE code = $1 AND tenant_id = $2
`

type GetRoleByCodeParams struct {
	Code     *string   `json:"code"`
	TenantID uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetRoleByCode(ctx context.Context, arg GetRoleByCodeParams) (Roles, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, arg.Code, arg.TenantID)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.IsSystem,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, tenant_id, name, code, description, created_at, is_system FROM roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (Roles, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.IsSystem,
	)
	return i, err
}

const getSystemRoleByCode = `-- name: GetSystemRoleByCode :one
SELECT id, tenant_id, name, code, description, created_at, is_system FROM roles
WHERE code = $1 
  AND is_system = TRUE 
  AND tenant_id IN (SELECT id FROM tenants WHERE kind = 'ops')
LIMIT 1
`

func (q *Queries) GetSystemRoleByCode(ctx context.Context, code *string) (Roles, error) {
	row := q.db.QueryRow(ctx, getSystemRoleByCode, code)
	var i Roles
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.IsSystem,
	)
	return i, err
}

const listAllRoles = `-- name: ListAllRoles :many
SELECT id, tenant_id, name, code, description, created_at, is_system FROM roles
ORDER BY created_at DESC
`

func (q *Queries) ListAllRoles(ctx context.Context) ([]Roles, error) {
	rows, err := q.db.Query(ctx, listAllRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Roles{}
	for rows.Next() {
		var i Roles
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModules = `-- name: ListModules :many
SELECT id, code, name, description, created_at FROM modules ORDER BY code ASC
`

func (q *Queries) ListModules(ctx context.Context) ([]Modules, error) {
	rows, err := q.db.Query(ctx, listModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Modules{}
	for rows.Next() {
		var i Modules
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, key, description, module, module_id FROM permissions ORDER BY key ASC
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permissions, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permissions{}
	for rows.Next() {
		var i Permissions
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.Module,
			&i.ModuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissionsByModule = `-- name: ListPermissionsByModule :many
SELECT id, key, description, module, module_id FROM permissions WHERE module_id = $1 ORDER BY key ASC
`

func (q *Queries) ListPermissionsByModule(ctx context.Context, moduleID pgtype.UUID) ([]Permissions, error) {
	rows, err := q.db.Query(ctx, listPermissionsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permissions{}
	for rows.Next() {
		var i Permissions
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.Module,
			&i.ModuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolePermissions = `-- name: ListRolePermissions :many
SELECT p.id, p.key, p.description, p.module, p.module_id FROM permissions p
JOIN role_permissions rp ON p.id = rp.permission_id
WHERE rp.role_id = $1
`

func (q *Queries) ListRolePermissions(ctx context.Context, roleID uuid.UUID) ([]Permissions, error) {
	rows, err := q.db.Query(ctx, listRolePermissions, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permissions{}
	for rows.Next() {
		var i Permissions
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.Module,
			&i.ModuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, tenant_id, name, code, description, created_at, is_system FROM roles
WHERE tenant_id = $1
   OR (tenant_id IN (SELECT id FROM tenants WHERE kind = 'ops') AND is_system = TRUE)
ORDER BY created_at DESC
`

func (q *Queries) ListRoles(ctx context.Context, tenantID uuid.UUID) ([]Roles, error) {
	rows, err := q.db.Query(ctx, listRoles, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Roles{}
	for rows.Next() {
		var i Roles
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTenantModules = `-- name: ListTenantModules :many
SELECT m.id, m.code, m.name, m.description, m.created_at FROM modules m
JOIN tenant_modules tm ON m.id = tm.module_id
WHERE tm.tenant_id = $1
`

func (q *Queries) ListTenantModules(ctx context.Context, tenantID uuid.UUID) ([]Modules, error) {
	rows, err := q.db.Query(ctx, listTenantModules, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Modules{}
	for rows.Next() {
		var i Modules
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT r.id, r.tenant_id, r.name, r.code, r.description, r.created_at, r.is_system FROM roles r
                    JOIN user_roles ur ON r.id = ur.role_id
WHERE ur.user_id = $1
`

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]Roles, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Roles{}
	for rows.Next() {
		var i Roles
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePermissionFromRole = `-- name: RemovePermissionFromRole :exec
DELETE FROM role_permissions
WHERE role_id = $1 AND permission_id = $2
`

type RemovePermissionFromRoleParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) RemovePermissionFromRole(ctx context.Context, arg RemovePermissionFromRoleParams) error {
	_, err := q.db.Exec(ctx, removePermissionFromRole, arg.RoleID, arg.PermissionID)
	return err
}

const removeRoleFromUser = `-- name: RemoveRoleFromUser :exec
DELETE FROM user_roles
WHERE user_id = $1 AND role_id = $2
`

type RemoveRoleFromUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	RoleID uuid.UUID `json:"role_id"`
}

func (q *Queries) RemoveRoleFromUser(ctx context.Context, arg RemoveRoleFromUserParams) error {
	_, err := q.db.Exec(ctx, removeRoleFromUser, arg.UserID, arg.RoleID)
	return err
}

const updateModule = `-- name: UpdateModule :exec
UPDATE modules SET name = $2, description = $3 WHERE id = $1
`

type UpdateModuleParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

func (q *Queries) UpdateModule(ctx context.Context, arg UpdateModuleParams) error {
	_, err := q.db.Exec(ctx, updateModule, arg.ID, arg.Name, arg.Description)
	return err
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE permissions
SET key = $2, description = $3, module = $4, module_id = $5
WHERE id = $1
`

type UpdatePermissionParams struct {
	ID          uuid.UUID   `json:"id"`
	Key         string      `json:"key"`
	Description *string     `json:"description"`
	Module      string      `json:"module"`
	ModuleID    pgtype.UUID `json:"module_id"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.Exec(ctx, updatePermission,
		arg.ID,
		arg.Key,
		arg.Description,
		arg.Module,
		arg.ModuleID,
	)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles
SET name = $3, description = $4, code = $5
WHERE id = $1 AND tenant_id = $2
`

type UpdateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	TenantID    uuid.UUID `json:"tenant_id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Code        *string   `json:"code"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.Code,
	)
	return err
}

const upsertModule = `-- name: UpsertModule :one

INSERT INTO modules (id, code, name, description)
VALUES ($1, $2, $3, $4)
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    description = EXCLUDED.description
RETURNING id, code, name, description, created_at
`

type UpsertModuleParams struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
}

// Modules
func (q *Queries) UpsertModule(ctx context.Context, arg UpsertModuleParams) (Modules, error) {
	row := q.db.QueryRow(ctx, upsertModule,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
	)
	var i Modules
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPermission = `-- name: UpsertPermission :one
INSERT INTO permissions (id, key, description, module, module_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (module, key) DO UPDATE SET
    description = EXCLUDED.description
RETURNING id, key, description, module, module_id
`

type UpsertPermissionParams struct {
	ID          uuid.UUID   `json:"id"`
	Key         string      `json:"key"`
	Description *string     `json:"description"`
	Module      string      `json:"module"`
	ModuleID    pgtype.UUID `json:"module_id"`
}

func (q *Queries) UpsertPermission(ctx context.Context, arg UpsertPermissionParams) (Permissions, error) {
	row := q.db.QueryRow(ctx, upsertPermission,
		arg.ID,
		arg.Key,
		arg.Description,
		arg.Module,
		arg.ModuleID,
	)
	var i Permissions
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Description,
		&i.Module,
		&i.ModuleID,
	)
	return i, err
}
