// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO fosite_sessions (
    signature,
    request_id,
    client_id,
    tenant_id,
    subject,
    type,
    active,
    requested_at,
    expires_at,
    form_data,
    session_data
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
         )
`

type CreateSessionParams struct {
	Signature   string          `json:"signature"`
	RequestID   string          `json:"request_id"`
	ClientID    string          `json:"client_id"`
	TenantID    uuid.UUID       `json:"tenant_id"`
	Subject     string          `json:"subject"`
	Type        string          `json:"type"`
	Active      bool            `json:"active"`
	RequestedAt time.Time       `json:"requested_at"`
	ExpiresAt   time.Time       `json:"expires_at"`
	FormData    json.RawMessage `json:"form_data"`
	SessionData json.RawMessage `json:"session_data"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.Signature,
		arg.RequestID,
		arg.ClientID,
		arg.TenantID,
		arg.Subject,
		arg.Type,
		arg.Active,
		arg.RequestedAt,
		arg.ExpiresAt,
		arg.FormData,
		arg.SessionData,
	)
	return err
}

const deleteSessionByType = `-- name: DeleteSessionByType :execrows
DELETE FROM fosite_sessions
WHERE signature = $1 AND type = $2
`

type DeleteSessionByTypeParams struct {
	Signature string `json:"signature"`
	Type      string `json:"type"`
}

func (q *Queries) DeleteSessionByType(ctx context.Context, arg DeleteSessionByTypeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByType, arg.Signature, arg.Type)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSession = `-- name: GetSession :one
SELECT signature, type, request_id, client_id, tenant_id, subject, active, requested_at, expires_at, form_data, session_data FROM fosite_sessions
WHERE signature = $1 AND type = $2
`

type GetSessionParams struct {
	Signature string `json:"signature"`
	Type      string `json:"type"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (FositeSessions, error) {
	row := q.db.QueryRow(ctx, getSession, arg.Signature, arg.Type)
	var i FositeSessions
	err := row.Scan(
		&i.Signature,
		&i.Type,
		&i.RequestID,
		&i.ClientID,
		&i.TenantID,
		&i.Subject,
		&i.Active,
		&i.RequestedAt,
		&i.ExpiresAt,
		&i.FormData,
		&i.SessionData,
	)
	return i, err
}

const revokeSessionByRequestId = `-- name: RevokeSessionByRequestId :exec
UPDATE fosite_sessions
SET active = false
WHERE request_id = $1
`

func (q *Queries) RevokeSessionByRequestId(ctx context.Context, requestID string) error {
	_, err := q.db.Exec(ctx, revokeSessionByRequestId, requestID)
	return err
}

const revokeSessionByRequestIdAndType = `-- name: RevokeSessionByRequestIdAndType :exec
UPDATE fosite_sessions
SET active = false
WHERE request_id = $1 AND type = $2
`

type RevokeSessionByRequestIdAndTypeParams struct {
	RequestID string `json:"request_id"`
	Type      string `json:"type"`
}

func (q *Queries) RevokeSessionByRequestIdAndType(ctx context.Context, arg RevokeSessionByRequestIdAndTypeParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByRequestIdAndType, arg.RequestID, arg.Type)
	return err
}
