// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
    id,
    name,
    kind,
    trial_ends_at,
    subscription_plan
) VALUES (
             $1, $2, $3, $4, $5
         )
RETURNING id, name, kind, created_at, updated_at, trial_ends_at, subscription_plan
`

type CreateTenantParams struct {
	ID               uuid.UUID          `json:"id"`
	Name             string             `json:"name"`
	Kind             TenantKind         `json:"kind"`
	TrialEndsAt      pgtype.Timestamptz `json:"trial_ends_at"`
	SubscriptionPlan *string            `json:"subscription_plan"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenants, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.Kind,
		arg.TrialEndsAt,
		arg.SubscriptionPlan,
	)
	var i Tenants
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrialEndsAt,
		&i.SubscriptionPlan,
	)
	return i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants
WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenant = `-- name: GetTenant :one
SELECT id, name, kind, created_at, updated_at, trial_ends_at, subscription_plan FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenant(ctx context.Context, id uuid.UUID) (Tenants, error) {
	row := q.db.QueryRow(ctx, getTenant, id)
	var i Tenants
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TrialEndsAt,
		&i.SubscriptionPlan,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, name, kind, created_at, updated_at, trial_ends_at, subscription_plan FROM tenants
ORDER BY created_at DESC
`

func (q *Queries) ListTenants(ctx context.Context) ([]Tenants, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenants{}
	for rows.Next() {
		var i Tenants
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TrialEndsAt,
			&i.SubscriptionPlan,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :exec
UPDATE tenants
SET name = $2, subscription_plan = $3, updated_at = NOW()
WHERE id = $1
`

type UpdateTenantParams struct {
	ID               uuid.UUID `json:"id"`
	Name             string    `json:"name"`
	SubscriptionPlan *string   `json:"subscription_plan"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) error {
	_, err := q.db.Exec(ctx, updateTenant, arg.ID, arg.Name, arg.SubscriptionPlan)
	return err
}
