// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (
  id,
  user_id,
  token,
  ip_address,
  user_agent,
  expires_at
) VALUES (
  $1, $2, $3, $4, $5, $6
)
RETURNING id, user_id, token, ip_address, user_agent, expires_at, created_at, updated_at
`

type CreateUserSessionParams struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSessions, error) {
	row := q.db.QueryRow(ctx, createUserSession,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.IpAddress,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i UserSessions
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserSession = `-- name: DeleteUserSession :exec
DELETE FROM user_sessions
WHERE token = $1
`

func (q *Queries) DeleteUserSession(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteUserSession, token)
	return err
}

const deleteUserSessionsByUserID = `-- name: DeleteUserSessionsByUserID :exec
DELETE FROM user_sessions
WHERE user_id = $1
`

func (q *Queries) DeleteUserSessionsByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessionsByUserID, userID)
	return err
}

const getUserSessionByToken = `-- name: GetUserSessionByToken :one
SELECT s.id, s.user_id, s.token, s.ip_address, s.user_agent, s.expires_at, s.created_at, s.updated_at, u.tenant_id
FROM user_sessions s
JOIN users u ON s.user_id = u.id
WHERE s.token = $1 LIMIT 1
`

type GetUserSessionByTokenRow struct {
	ID        uuid.UUID `json:"id"`
	UserID    uuid.UUID `json:"user_id"`
	Token     string    `json:"token"`
	IpAddress *string   `json:"ip_address"`
	UserAgent *string   `json:"user_agent"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	TenantID  uuid.UUID `json:"tenant_id"`
}

func (q *Queries) GetUserSessionByToken(ctx context.Context, token string) (GetUserSessionByTokenRow, error) {
	row := q.db.QueryRow(ctx, getUserSessionByToken, token)
	var i GetUserSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.IpAddress,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TenantID,
	)
	return i, err
}
