// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationChallenge = `-- name: CreateVerificationChallenge :one
INSERT INTO verification_challenges (
    id,
    tenant_id,
    user_id,
    kind,
    token_hash,
    expires_at
) VALUES (
             $1, $2, $3, $4, $5, $6
         )
RETURNING id, tenant_id, user_id, kind, token_hash, expires_at, consumed_at, created_at
`

type CreateVerificationChallengeParams struct {
	ID        uuid.UUID `json:"id"`
	TenantID  uuid.UUID `json:"tenant_id"`
	UserID    uuid.UUID `json:"user_id"`
	Kind      string    `json:"kind"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateVerificationChallenge(ctx context.Context, arg CreateVerificationChallengeParams) (VerificationChallenges, error) {
	row := q.db.QueryRow(ctx, createVerificationChallenge,
		arg.ID,
		arg.TenantID,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i VerificationChallenges
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :exec
DELETE FROM verification_challenges
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredChallenges)
	return err
}

const getVerificationChallenge = `-- name: GetVerificationChallenge :one
SELECT id, tenant_id, user_id, kind, token_hash, expires_at, consumed_at, created_at FROM verification_challenges
WHERE user_id = $1 AND kind = $2 AND consumed_at IS NULL AND expires_at > NOW()
`

type GetVerificationChallengeParams struct {
	UserID uuid.UUID `json:"user_id"`
	Kind   string    `json:"kind"`
}

func (q *Queries) GetVerificationChallenge(ctx context.Context, arg GetVerificationChallengeParams) (VerificationChallenges, error) {
	row := q.db.QueryRow(ctx, getVerificationChallenge, arg.UserID, arg.Kind)
	var i VerificationChallenges
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getVerificationChallengeByToken = `-- name: GetVerificationChallengeByToken :one
SELECT id, tenant_id, user_id, kind, token_hash, expires_at, consumed_at, created_at FROM verification_challenges
WHERE token_hash = $1 AND kind = $2 AND consumed_at IS NULL AND expires_at > NOW()
`

type GetVerificationChallengeByTokenParams struct {
	TokenHash string `json:"token_hash"`
	Kind      string `json:"kind"`
}

func (q *Queries) GetVerificationChallengeByToken(ctx context.Context, arg GetVerificationChallengeByTokenParams) (VerificationChallenges, error) {
	row := q.db.QueryRow(ctx, getVerificationChallengeByToken, arg.TokenHash, arg.Kind)
	var i VerificationChallenges
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markChallengeConsumed = `-- name: MarkChallengeConsumed :exec
UPDATE verification_challenges
SET consumed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkChallengeConsumed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markChallengeConsumed, id)
	return err
}
